PackageIdentifier: debanjanbasu.grr
PackageVersion: 0.11.1
InstallerType: zip
Installers:
  - Architecture: arm64
    InstallerType: zip
    InstallerUrl: https://github.com/debanjanbasu/grr-cli/releases/download/v0.11.1/grr-v0.11.1-windows-aarch64.zip
    InstallerSha256: 34DFEA17E8C2C24407A073BAB482AC4607B5FBFB6DA4FBA334CBB7BDF2EE83F4
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: grr.exe
        PortableCommandAlias: grr
    ReleaseDate: 2026-10-05
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/debanjanbasu/grr-cli/releases/download/v0.11.1/grr-v0.11.1-windows-x86_64.zip
    InstallerSha256: 4514138D49D11041970033424CB3AEB555B70A0DBB134FB99A24B95F46669E27
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: grr.exe
        PortableCommandAlias: grr
    ReleaseDate: 2026-10-05
ManifestType: installer
ManifestVersion: 1.6.0
