PackageIdentifier: debanjanbasu.grr
PackageVersion: 0.10.0
InstallerType: zip
Installers:
  - Architecture: arm64
    InstallerType: zip
    InstallerUrl: https://github.com/debanjanbasu/grr-cli/releases/download/v0.10.0/grr-v0.10.0-windows-aarch64.zip
    InstallerSha256: 436A617428528FC6DAFB34B51BC6591560C63AA87746456E10AD213611B4120B
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: grr.exe
        PortableCommandAlias: grr
    ReleaseDate: 2026-10-04
  - Architecture: x64
    InstallerType: zip
    InstallerUrl: https://github.com/debanjanbasu/grr-cli/releases/download/v0.10.0/grr-v0.10.0-windows-x86_64.zip
    InstallerSha256: 5CD6A72AAB84007364F387492C2B8CA77225E34CA2749767BAD4806B41560FFD
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: grr.exe
        PortableCommandAlias: grr
    ReleaseDate: 2026-10-04
ManifestType: installer
ManifestVersion: 1.6.0
